// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlrctcvitqvwdydpcmex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRscmN0Y3ZpdHF2d2R5ZHBjbWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkxMjM5NzgsImV4cCI6MjA4NDY5OTk3OH0.iPq1sK633wNMSRvSjqIrY7-hl5twBcyCvaLqIdiPkBM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});